PROGRAM SALIM

IMPLICIT NONE

REAL:: TEMP_IN_CELCIUS(10),TEMP_IN_KELVIN(10)
INTEGER:: K
OPEN(1,file="Air-Temperature.csv",status="old")
DO k=1,10
READ(1,*) TEMP_IN_CELCIUS
TEMP_IN_KELVIN= TEMP_IN_CELCIUS+273.15
END DO
 CLOSE(1)
OPEN(10,file="8678321_Air-Temperature-Assignment.csv",status="new")
DO k=1,10
WRITE(10,*)TEMP_IN_KELVIN
END DO
 CLOSE(10)
END PROGRAM SALIM

